# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e29f0b0decb588e6cbec1f6123af168530241cbd205358ae2f04987427915e7f8340197e5a051c8264335c5f76cadd9632d98b1b40e4fba12aae58ae17f93df

test:
  secret_key_base: 329e7f446765e1b01793c03ed80ea2c15c68155a8068566e9ac4e69e736db4162c4f6e0b2c7b4e244d5cda7a6fbc1f771919f6de451c31f3fa34c20881734703

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
